### ISSUE TITLE
Script fails (noob alert!)

### ISSUE THREAD

**Issue by matrhein** [renerocksai/rj2obs#1]
Hi Rene, 

I managed to install python through homebrew and run your script through the terminal, however, that is the utmost extent of my terminal knowledge. It returns the following error after I installed the dependencies and ran r2o with the command from the readme and my json export in the same folder:

```
unknownA483E7267758:rj2obs-main mat_rhein$ python r2o.py Matroam.json
  File "r2o.py", line 65
    replacement += f' [[{r_block["page"]["title"]}#^{r_block["uid"]}]]'                                 
SyntaxError: invalid syntax
```

Please advise me as to what I am doing wrong.
Cheers, Mat

**Comment by lkhphuc** [comment]
Hi @matrhein , invalid syntax means that you get a python version incompatible version.
Make sure you have the latest version of python 3.9 (or at least above 3.7) to have the syntax for f-string.

**Comment by renerocksai** [comment]
try to run the script with the `python3` command instead of the `python` command. This will tell you if you have python 3 installed. If not, try homebrew or python.org to get a more recent python.

Since python2 is officially outdated since 2020, I didn't expect ppl to still use it.
