### ISSUE TITLE
KeyError: 'edit-time' on line 122

### ISSUE THREAD

**Issue by jeremy-allen** [renerocksai/rj2obs#11]
First, THANK YOU for helping many of us who want to use Roam and Obsidian!

I got python 3.9.6 installed from homebrew using pyenv, then pip3 to install your requirements. Then, `python3 r2o.py my_file.json` returns this error:

```
Pass 1: scan all pages
  0%|                                                                                          | 0/1135 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/Users/blah/r2o.py", line 122, in <module>
    created = page.get('create-time', page['edit-time'])
KeyError: 'edit-time'
```

Suggestions?

**Comment by reagantrose** [comment]
I'm having this same issue. Did you find a way to resolve it?

**Comment by mrjano** [comment]
I had this same issue, looks like some pages in the Roam export don't have create-time/edit-time values

Just replace

`created = page.get('create-time', page['edit-time'])`

with

```created = page.get('create-time', page.get('edit-time', 0))```

be aware that the created time on some pages may be off

**Comment by arinazari** [comment]
I get the error this user gets after making that edit: https://github.com/renerocksai/rj2obs/issues/7

**Comment by jonathanhung** [comment]
Tried this and resulted in 

`uid not found: Bnl7-UQg1`
