### ISSUE TITLE
Script output (not sure what is expected)

### ISSUE THREAD

**Issue by kiraarghy** [renerocksai/rj2obs#5]
Thank you so much for the work on this, you've saved me quite a few hours migrating from Roam to Obsidian!

I'm currently running the script and it's taking a long time to execute, which I understand cause it's probably doing a lot. 

However it is constantly spitting out the message on:

https://github.com/renerocksai/rj2obs/blob/3468d50ad3e42866c73fc512e0a079d22dec83c3/r2o.py#L57-L59

Is that to be expected? I'm not sure if the code is in an infinite loop, or it's waiting till it parses that block as part of the first run?

Thanks again!

**Comment by renerocksai** [comment]
Chances are, Roam changed sth in the blockref department. The script shouldn't take very long unless your database is really huge.

Do you have more info?

**Comment by kiraarghy** [comment]
From debugging, it seems like it's the same uid causing a loop to form. 

I'll have a look into the blockref changes and if I find anything out I'll get back to you!

**Comment by kiraarghy** [comment]
Looking into it @lkhphuc's PR'ed fix with the break clause worked for me https://github.com/renerocksai/rj2obs/pull/2!
