### ISSUE TITLE
I think the JSON format for Roam is different now

### ISSUE THREAD

**Issue by classicrob** [renerocksai/rj2obs#6]
This is the output I get when I run the program

![image](https://user-images.githubusercontent.com/46608303/112639422-dbe30100-8e05-11eb-892f-cd07664027bd.png)

**Comment by renerocksai** [comment]
Just saw your message - are you using python3? A syntax error usually
occurs when the script is broken, not the data it receives. So my bet is,
you're using some old python3, maybe the one that came with your Mac.

Check out homebrew or python.org on how to install a current version of
python (3.x).

Python2 is no longer supported.

classicrob ***@***.***> schrieb am Fr., 26. März 2021, 14:36:

**Comment by renerocksai** [comment]
Seems like python2 -> please use python3. Python2 has been dead officially for a year now.

**Comment by renerocksai** [comment]
also, I had a typo here

> So my bet is, you're using some old python3, maybe the one that came with your Mac.

should have read:

So my bet is, you're using some old python**2**, maybe the one that came with your Mac.
